#!/bin/bash

# Script to automatically update a drupal module (without doing backups, which you shouldn't do)

if [ $# -lt 2 ]; then
  echo "Usage: $0 drupal_root_folder [module file]"
  exit
fi

DRUPAL_FTP=http://ftp.drupal.org/files/projects/
FILE=$2
DESTINATION=$1

cd $DESTINATION/modules
wget $DRUPAL_FTP$FILE
tar xzf $FILE
rm -f $FILE
cd ../..
